### ISSUE TITLE
Support for stdin

### ISSUE THREAD

**Issue by Lutitious** [uncenter/kittysay#6]
Add support for stdin like in cowsay,

For example you could use `echo 'nya' | kittysay` or maybe with a special flag `echo 'nya' | kittysay -s` to pass in the outputs of other programs. This is very useful for scripting or when you want your fetch to be said by a cute kitty.

**Comment by uncenter** [comment]
You can! You have to add a dash (`-`) as an argument like this: `echo ":3" | kittysay -`.

**Comment by uncenter** [comment]
FYI you now no longer need the extra `-` argument in v0.6.0 :)
